name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-x86:
    runs-on: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
    - name: Featutes
      run: cargo run --bin cpu_features
    # - name: Test
    #   run: cargo test --verbose

  test-arm:
    runs-on: [ubuntu-24.04-arm]

    steps:
    - uses: actions/checkout@v4
    - name: Featutes
      run: cargo run --bin cpu_features
